import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import { useEvervault } from '@evervault/react';

const EvervaultProvider = dynamic(() => import('@evervault/react').then((mod) => mod.EvervaultProvider))

const Last4DigitsInput = () => {
  const isServerSide = typeof window === 'undefined';

  if (isServerSide) {
    return null;
  }

  return <EvervaultProvider teamId={"d7664f0891ca"}>
    <div id={"form-cc"}></div>
  </EvervaultProvider>
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Evervault
        </h1>
        <Last4DigitsInput/>

      </main>
    </div>
  )
}

